import { Router } from 'express';
import authRoutes from './auth.routes';
import productRoutes from './product.routes';
import customerRoutes from './customer.routes';
import warehouseRoutes from './warehouse.routes';
import stockRoutes from './stock.routes';
import pricingRoutes from './pricing.routes';
import discountRoutes from './discount.routes';
import approvalConfigRoutes from './approval-config.routes';
import upsellConfigRoutes from './upsell-config.routes';
import quotationRoutes from './quotation.routes';
import approvalRoutes from './approval.routes';
import fulfillmentRoutes from './fulfillment.routes';
import subscriptionRoutes from './subscription.routes';
import invoiceRoutes from './invoice.routes';
import paymentRoutes from './payment.routes';
import portalRoutes from './portal.routes';
import auditRoutes from './audit.routes';
import riskScoreRoutes from './risk-score.routes';
import upsellSuggestionsRoutes from './upsell-suggestions.routes';
import dealHealthRoutes from './deal-health.routes';
import cronRoutes from './cron.routes';
import aiRoutes from './ai.routes';

export const routes = Router();

routes.use('/auth', authRoutes);
routes.use('/products', productRoutes);
routes.use('/customers', customerRoutes);
routes.use('/warehouses', warehouseRoutes);
routes.use('/stock', stockRoutes);
routes.use('/pricing', pricingRoutes);
routes.use('/discounts', discountRoutes);
routes.use('/approval-chains', approvalConfigRoutes);
routes.use('/upsell-rules', upsellConfigRoutes);
routes.use('/quotations', quotationRoutes);
routes.use('/approvals', approvalRoutes);
routes.use('/fulfillment', fulfillmentRoutes);
routes.use('/subscriptions', subscriptionRoutes);
routes.use('/invoices', invoiceRoutes);
routes.use('/payments', paymentRoutes);
routes.use('/portal', portalRoutes);
routes.use('/audit-log', auditRoutes);
routes.use('/risk-score', riskScoreRoutes);
routes.use('/upsell-suggestions', upsellSuggestionsRoutes);
routes.use('/deal-health-flags', dealHealthRoutes);
routes.use('/cron', cronRoutes);
routes.use('/ai', aiRoutes);
